const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const LOGOUT = 'LOGOUT';

export { LOGIN_LOADING, LOGIN_SUCCESS, LOGIN_ERROR, LOGOUT };
