// // const ADD_COUNT_LOADING = 'ADD_COUNT_LOADING';
// // const ADD_COUNT_SUCCESS = 'ADD_COUNT_SUCCESS';
// // const ADD_COUNT_ERROR = 'ADD_COUNT_ERROR';

// // const SUB_COUNT_LOADING = 'SUB_COUNT_LOADING';
// // const SUB_COUNT_SUCCESS = 'SUB_COUNT_SUCCESS';
// // const SUB_COUNT_ERROR = 'SUB_COUNT_ERROR';

// <<<<<<< HEAD
// // export { ADD_COUNT_LOADING, ADD_COUNT_SUCCESS, ADD_COUNT_ERROR,SUB_COUNT_LOADING,SUB_COUNT_SUCCESS,SUB_COUNT_ERROR };
// =======
// export { ADD_COUNT_LOADING, ADD_COUNT_SUCCESS, ADD_COUNT_ERROR };

// export { SUB_COUNT_LOADING, SUB_COUNT_SUCCESS, SUB_COUNT_ERROR };
// >>>>>>> 73840be01b6c382860ea910c52c838c579fde4b8
