const ADD_COUNT_LOADING = 'ADD_COUNT_LOADING';
const ADD_COUNT_SUCCESS = 'ADD_COUNT_SUCCESS';
const ADD_COUNT_ERROR = 'ADD_COUNT_ERROR';

export { ADD_COUNT_LOADING, ADD_COUNT_SUCCESS, ADD_COUNT_ERROR };
